source "https://supermarket.getchef.com"

cookbook 'python', git: 'https://github.com/poise/python.git'
cookbook 'mariadb', git: 'https://github.com/joerocklin/chef-mariadb.git'
cookbook 'nginx', git: 'https://github.com/miketheman/nginx.git'
