source "https://supermarket.getchef.com"

# cookbook 'python', git: 'https://github.com/poise/python.git'
cookbook 'python'
# cookbook 'mariadb', git: 'https://github.com/joerocklin/chef-mariadb.git'
# cookbook 'nginx', git: 'https://github.com/miketheman/nginx.git'
cookbook 'nginx'

# cookbook 'mysql', git: 'https://github.com/opscode-cookbooks/mysql.git'
# cookbook 'database', git: 'https://github.com/opscode-cookbooks/database.git'
cookbook 'mysql', '= 5.5.3'
cookbook 'database'
